title: Hanif Wicaksono Suryohusodo
logo: "assets/1.png"
$escription: Hanif Wicaksono Suryohusodo | Software Engineer Enthusiast | Student at Batam State Polytechnic
show_downloads: true
remote_theme: pages-themes/minimal@v0.2.0
